server {
    listen 80;
    server_name localhost;

    # Rutas del Backend (API, Sanctum, Admin Panel, Auth, etc)
    location ~ ^/(api|admin|dashboard|profile|magic-login|sanctum|login|logout|register|storage|build|_debugbar) {
        proxy_pass http://api.burguermarina.internal:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend: Redirigir el resto de peticiones al contenedor de Angular (SSR) local
    location / {
        proxy_pass http://frontend_node:4200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Soporte para WebSockets (útil para el modo desarrollo de Angular)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Opcional: Aumentar el tamaño máximo de subida (para fotos de platos, etc.)
    client_max_body_size 20M;
}
