server {
    listen 80;
    server_name burguermarina.duckdns.org localhost;

    # Redirigir todo el tráfico HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name burguermarina.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/burguermarina.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/burguermarina.duckdns.org/privkey.pem;

    # Configuraciones recomendadas para SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Rutas del Backend (API, Sanctum, Admin Panel, Auth, etc)
    location ~ ^/(api|admin|dashboard|profile|magic-login|sanctum|logout|storage|build|_debugbar) {
        proxy_pass http://api.burguermarina.internal:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend: Redirigir el resto de peticiones al contenedor de Angular (SSR) local
    location / {
        proxy_pass http://frontend_node:4200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Soporte para WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Opcional: Aumentar el tamaño máximo de subida
    client_max_body_size 20M;
}
