name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/Proyecto-final"

    - name: Execute Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/Proyecto-final
          # Ajustamos la URL de la aplicación para que las redirecciones al blade funcionen
          sed -i 's|APP_URL=http://localhost|APP_URL=http://54.160.77.44|g' backend/.env
          docker-compose run --rm workspace sh -c "cd frontend && npm install && npm run build"

          # Detener posibles servicios en el host que usen el puerto 80
          sudo systemctl stop nginx || true
          sudo systemctl stop apache2 || true

          # lo finalizamos
          sudo fuser -k 80/tcp || true

          # Desplegamos con Docker Compose
          docker-compose down
          docker-compose up -d --build

          # Aseguramos que la base de datos tenga los datos (admin, platos, etc.)
          sleep 15
          docker exec entorno_trabajo php backend/artisan migrate:fresh --seed --force
