name: Deploy to EC2 (Front & Back Separados)

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy files via SSH (Backend)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_BACKEND_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ".,!frontend/node_modules,!backend/vendor,!.git,!.angular"
        target: "~/Proyecto-final"

    - name: Execute Docker Compose (Backend)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_BACKEND_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/Proyecto-final
          
          cat << 'EOF' > backend/.env
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=base64:mI+0g9Y4DznAxRNUg0DqaI9SabqOb72GQ7OaLCQoPOM=
          APP_DEBUG=false
          APP_URL=http://${{ secrets.EC2_FRONTEND_HOST }}

          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=proyecto_db
          DB_USERNAME=root
          DB_PASSWORD=root
          EOF

          docker compose -f docker-compose.back.yml down
          docker compose -f docker-compose.back.yml up -d --build
          
          sleep 40
          docker exec entorno_trabajo php backend/artisan migrate:fresh --seed --force

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy files via SSH (Frontend)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_FRONTEND_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ".,!frontend/node_modules,!backend/vendor,!.git,!.angular"
        target: "~/Proyecto-final"

    - name: Execute Docker Compose (Frontend)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_FRONTEND_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/Proyecto-final
          docker compose -f docker-compose.front.yml down
          docker compose -f docker-compose.front.yml up -d --build
