name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/Proyecto-final"

    - name: Execute Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/Proyecto-final
          #con esto paramos  lo que haya en el puerto 80
          sudo systemctl stop nginx || true
          sudo systemctl stop apache2 || true
          # 2. lo finalizamos
          sudo fuser -k 80/tcp || true
          # 3. Desplegamos con Docker Compose
          docker-compose down
          docker-compose up -d --build
